export const initialUsers = [
  {
    id: "user_1",
    name: "רועי כהן",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80",
    xp: 2450,
    rank: 1,
    completedChallengesCount: 18,
    badges: [
      "🔥 רצף של 7 ימים", 
      "🏃 מרתוניסט", 
      "⛰️ כובש פסגות", 
      "💪 איש הברזל", 
      "⚡ זריז במיוחד", 
      "🧗 כובש החרמון", 
      "❄️ איש הקרח", 
      "🏊 צולח הכנרת", 
      "🌅 מטפס מצדה", 
      "🐠 כריש המפרץ", 
      "🐺 זאב הערבה", 
      "🇮🇱 שביליסט מוסמך", 
      "🏜️ נווד המדבר", 
      "🧘 רוח טהורה", 
      "🔱 הרקולס", 
      "☯️ מסטר יוגה"
    ],
    activeChallenges: ["run_10k", "pushups_100"],
    reportsCount: 0,
    isBlocked: false,
    hardChallengesCompleted: 3,
    streak: 7,
    followers: ["user_2", "user_3", "user_5", "user_7"],
    following: ["user_2", "user_4", "user_6"],
    stats: { strength: 78, stamina: 85, agility: 62, zen: 45 }
  },
  {
    id: "user_2",
    name: "יובל לוי",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=80",
    xp: 1980,
    rank: 2,
    completedChallengesCount: 14,
    badges: ["💪 איש הברזל", "⚡ זריז במיוחד"],
    activeChallenges: ["plank_30d"],
    reportsCount: 0,
    isBlocked: false,
    hardChallengesCompleted: 2,
    streak: 5,
    followers: ["user_1", "user_4", "user_6"],
    following: ["user_1", "user_3", "user_5"],
    stats: { strength: 90, stamina: 70, agility: 80, zen: 30 }
  },
  {
    id: "user_3",
    name: "דניאל מזרחי",
    avatar: "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=100&auto=format&fit=crop&q=80",
    xp: 1620,
    rank: 3,
    completedChallengesCount: 11,
    badges: ["🚲 מדווש על", "🏔️ חובב גבהים"],
    activeChallenges: ["run_10k", "plank_30d"],
    reportsCount: 0,
    isBlocked: false,
    hardChallengesCompleted: 1,
    streak: 3,
    followers: ["user_2"],
    following: ["user_1", "user_7"],
    stats: { strength: 65, stamina: 88, agility: 70, zen: 50 }
  },
  {
    id: "user_4",
    name: "שירה אלוני",
    avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&auto=format&fit=crop&q=80",
    xp: 1400,
    rank: 4,
    completedChallengesCount: 9,
    badges: ["🧘 יוגה מאסטר"],
    activeChallenges: ["pushups_100"],
    reportsCount: 0,
    isBlocked: false,
    hardChallengesCompleted: 0,
    streak: 12,
    followers: ["user_1"],
    following: ["user_2", "user_8"],
    stats: { strength: 50, stamina: 60, agility: 55, zen: 95 }
  },
  {
    id: "user_5",
    name: "נטע ברק",
    avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100&auto=format&fit=crop&q=80",
    xp: 1250,
    rank: 5,
    completedChallengesCount: 8,
    badges: ["🏊‍♀️ דולפין", "🌟 כוכב עולה"],
    activeChallenges: ["swim_2k"],
    reportsCount: 0,
    isBlocked: false,
    hardChallengesCompleted: 1,
    streak: 4,
    followers: ["user_2"],
    following: ["user_1"],
    stats: { strength: 55, stamina: 75, agility: 65, zen: 60 }
  },
  {
    id: "user_6",
    name: "גיא רגב",
    avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=100&auto=format&fit=crop&q=80",
    xp: 1100,
    rank: 6,
    completedChallengesCount: 7,
    badges: ["🏋️‍♂️ שור זועם"],
    activeChallenges: ["pullups_20"],
    reportsCount: 0,
    isBlocked: false,
    hardChallengesCompleted: 1,
    streak: 6,
    followers: ["user_1"],
    following: ["user_2"],
    stats: { strength: 85, stamina: 55, agility: 60, zen: 35 }
  },
  {
    id: "user_7",
    name: "מיכל אשד",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&auto=format&fit=crop&q=80",
    xp: 950,
    rank: 7,
    completedChallengesCount: 5,
    badges: ["🧘‍♀️ שקט פנימי"],
    activeChallenges: ["meditate_20m"],
    reportsCount: 0,
    isBlocked: false,
    hardChallengesCompleted: 0,
    streak: 8,
    followers: ["user_3"],
    following: ["user_1"],
    stats: { strength: 40, stamina: 50, agility: 50, zen: 85 }
  },
  {
    id: "user_8",
    name: "אלון גל",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&auto=format&fit=crop&q=80",
    xp: 880,
    rank: 8,
    completedChallengesCount: 4,
    badges: ["🚴‍♂️ רוכב רוח"],
    activeChallenges: ["cycle_50k"],
    reportsCount: 0,
    isBlocked: false,
    hardChallengesCompleted: 0,
    streak: 2,
    followers: ["user_4"],
    following: ["user_4"],
    stats: { strength: 60, stamina: 70, agility: 68, zen: 40 }
  }
];

export const initialNotifications = [
  {
    id: "notif_1",
    type: "follow",
    senderId: "user_4",
    senderName: "שירה אלוני",
    senderAvatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&auto=format&fit=crop&q=80",
    text: "התחילה לעקוב אחריך",
    timestamp: "לפני 10 דקות",
    read: false
  },
  {
    id: "notif_2",
    type: "joint_challenge",
    senderId: "user_2",
    senderName: "יובל לוי",
    senderAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=80",
    text: "הזמין אותך לאתגר משותף: 100 שכיבות סמיכה ברצף",
    challengeId: "pushups_100",
    timestamp: "לפני שעה",
    read: false,
    status: "pending" // pending, accepted, declined
  },
  {
    id: "notif_3",
    type: "like",
    senderId: "user_3",
    senderName: "דניאל מזרחי",
    senderAvatar: "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=100&auto=format&fit=crop&q=80",
    text: "אהב/ה את פוסט השלמת האתגר שלך: \"100 שכיבות סמיכה ברצף\" ❤️",
    timestamp: "לפני שעתיים",
    read: true
  },
  {
    id: "notif_4",
    type: "comment",
    senderId: "user_5",
    senderName: "נטע ברק",
    senderAvatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100&auto=format&fit=crop&q=80",
    text: "הגיב/ה על הפוסט שלך: \"מדהים! השראה לכולנו\" 💬",
    timestamp: "לפני יום",
    read: true
  },
  {
    id: "notif_5",
    type: "follow_approve",
    senderId: "user_6",
    senderName: "גיא רגב",
    senderAvatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=100&auto=format&fit=crop&q=80",
    text: "אישר/ה את בקשת המעקב שלך 🤝",
    timestamp: "לפני יומיים",
    read: true
  }
];

export const initialChallenges = [
  {
    id: "run_10k",
    title: "אתגר ריצת 10 קילומטר",
    description: "רוצו מרחק של 10 קילומטרים בקצב שלכם ותעדו את תוצאת האפליקציה או השעון.",
    category: "אירובי",
    difficulty: "בינוני",
    xpReward: 300,
    participantsCount: 47,
    duration: "חד פעמי",
    creator: "Pulse Team",
    image: "https://images.unsplash.com/photo-1476480862126-209bfaa8edc8?w=600&auto=format&fit=crop&q=80",
    difficultyGrades: [3, 4, 3, 2, 4],
    isIconic: false
  },
  {
    id: "pushups_100",
    title: "100 שכיבות סמיכה ברצף",
    description: "מבחן כוח אמיתי. בצעו 100 שכיבות סמיכה בסט אחד (או עם הפסקות קצרות של עד 5 שניות במצב פלאנק).",
    category: "כוח",
    difficulty: "קשה",
    xpReward: 500,
    participantsCount: 32,
    duration: "חד פעמי",
    creator: "רועי כהן",
    image: "https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=600&auto=format&fit=crop&q=80",
    difficultyGrades: [4, 5, 4, 5, 4],
    isIconic: false
  },
  {
    id: "plank_30d",
    title: "30 ימי פלאנק",
    description: "אתגר יומיומי: מתחילים מדקה ביום הראשון ומגיעים ל-5 דקות פלאנק ביום ה-30.",
    category: "ליבה",
    difficulty: "קל",
    xpReward: 400,
    participantsCount: 118,
    duration: "30 ימים",
    creator: "שירה אלוני",
    image: "https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=600&auto=format&fit=crop&q=80",
    difficultyGrades: [2, 2, 3, 1, 2],
    isIconic: false
  },
  {
    id: "climb_mount",
    title: "טיפוס לפסגת החרמון",
    description: "כבשו את הפסגה הגבוהה במדינה ברגל. העלו תמונה מציגת נוף ותחנת הרכבל העליונה.",
    category: "שטח",
    difficulty: "קשה מאוד",
    xpReward: 800,
    participantsCount: 14,
    duration: "חד פעמי",
    creator: "דניאל מזרחי",
    image: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=600&auto=format&fit=crop&q=80",
    difficultyGrades: [5, 5, 4, 5],
    isIconic: true,
    badgeReward: "🧗 כובש החרמון"
  },
  {
    id: "marathon_run",
    title: "ריצת מרתון שלם (42.2 ק\"מ)",
    description: "האתגר האולטימטיבי של הריצה. לרוץ 42.195 קילומטרים ולסיים בגאווה.",
    category: "אירובי",
    difficulty: "קשה מאוד",
    xpReward: 1000,
    participantsCount: 5,
    duration: "חד פעמי",
    creator: "Pulse Team",
    image: "https://images.unsplash.com/photo-1530541930197-ff16ac917b0e?w=600&auto=format&fit=crop&q=80",
    difficultyGrades: [5, 5, 5],
    isIconic: true,
    badgeReward: "🏅 מרתוניסט"
  },
  {
    id: "squat_500",
    title: "500 סקוואטים בשבוע",
    description: "אתגר סיבולת וכוח לפלג הגוף התחתון. בצעו 500 סקוואטים במצטבר לאורך השבוע.",
    category: "כוח",
    difficulty: "בינוני",
    xpReward: 350,
    participantsCount: 22,
    duration: "שבוע",
    creator: "שירה אלוני",
    image: "https://images.unsplash.com/photo-1574680096145-d05b474e2155?w=600&auto=format&fit=crop&q=80",
    difficultyGrades: [3, 3, 4],
    isIconic: false
  },
  {
    id: "cold_plunge",
    title: "טבילה באמבטיית קרח",
    description: "התאוששות מושלמת לשרירים ולנפש. הישארו בקרח לפחות 3 דקות רצופות.",
    category: "זן",
    difficulty: "קשה מאוד",
    xpReward: 600,
    participantsCount: 8,
    duration: "חד פעמי",
    creator: "Pulse Team",
    image: "https://images.unsplash.com/photo-1518310383802-640c2de311b2?w=600&auto=format&fit=crop&q=80",
    difficultyGrades: [5, 5, 4, 5],
    isIconic: true,
    badgeReward: "❄️ איש הקרח"
  },
  {
    id: "swim_2k",
    title: "שחיית 2 קילומטרים",
    description: "בצעו אימון שחייה רצוף בבריכה או בים הפתוח למרחק של 2000 מטר.",
    category: "אירובי",
    difficulty: "קשה",
    xpReward: 550,
    participantsCount: 19,
    duration: "חד פעמי",
    creator: "נטע ברק",
    image: "https://images.unsplash.com/photo-1600965962102-9d260a71890d?w=600&auto=format&fit=crop&q=80",
    difficultyGrades: [4, 4, 3],
    isIconic: false
  },
  {
    id: "cycle_50k",
    title: "רכיבת אופניים 50 ק\"מ",
    description: "צאו לרכיבה ארוכה בכביש או בשטח ותעדו מרחק של 50 קילומטרים לפחות.",
    category: "אירובי",
    difficulty: "קשה",
    xpReward: 650,
    participantsCount: 15,
    duration: "חד פעמי",
    creator: "אלון גל",
    image: "https://images.unsplash.com/photo-1485965120184-e220f721d03e?w=600&auto=format&fit=crop&q=80",
    difficultyGrades: [4, 5, 4],
    isIconic: false
  },
  {
    id: "meditate_20m",
    title: "20 דקות מדיטציה יומית",
    description: "שקט מנטלי בתוך השגרה הלחוצה. 20 דקות של ישיבה שקטה ונשימות מודעות בכל יום.",
    category: "זן",
    difficulty: "קל",
    xpReward: 250,
    participantsCount: 88,
    duration: "יומי",
    creator: "מיכל אשד",
    image: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=600&auto=format&fit=crop&q=80",
    difficultyGrades: [1, 2, 1, 2],
    isIconic: false
  },
  {
    id: "israman_eilat",
    title: "ישראמן אילת - איש ברזל מלא",
    description: "האתגר הפיזי הקשה בישראל. שחייה של 3.8 ק\"מ במפרץ אילת, רכיבה של 180 ק\"מ בעליות להרי אילת, וריצת מרתון מלא של 42.2 ק\"מ.",
    category: "אירובי",
    difficulty: "קשה מאוד",
    xpReward: 1500,
    participantsCount: 8,
    duration: "חד פעמי",
    creator: "התאחדות הטריאתלון",
    image: "https://images.unsplash.com/photo-1530541930197-ff16ac917b0e?w=600&auto=format&fit=crop&q=80",
    difficultyGrades: [5, 5, 5],
    isIconic: true,
    badgeReward: "🧬 איש ברזל ישראמן"
  },
  {
    id: "galilee_swim",
    title: "צליחת הכנרת הרשמית בשחייה",
    description: "שחו מקצה מלא לאורך הכנרת מחוף צמח לחוף עין גב (או מקצה עממי של 3 ק\"מ).",
    category: "אירובי",
    difficulty: "קשה",
    xpReward: 700,
    participantsCount: 45,
    duration: "חד פעמי",
    creator: "מועצה אזורית עמק הירדן",
    image: "https://images.unsplash.com/photo-1600965962102-9d260a71890d?w=600&auto=format&fit=crop&q=80",
    difficultyGrades: [4, 4, 4],
    isIconic: true,
    badgeReward: "🏊 צולח הכנרת"
  },
  {
    id: "ta_marathon",
    title: "מרתון תל אביב הרשמי",
    description: "ריצת מרתון מלא לאורך רחובותיה המרכזיים של תל אביב וטיילת החוף.",
    category: "אירובי",
    difficulty: "קשה מאוד",
    xpReward: 1000,
    participantsCount: 62,
    duration: "חד פעמי",
    creator: "עיריית תל אביב",
    image: "https://images.unsplash.com/photo-1476480862126-209bfaa8edc8?w=600&auto=format&fit=crop&q=80",
    difficultyGrades: [5, 4, 5],
    isIconic: true,
    badgeReward: "🏃‍♂️ אלוף תל אביב"
  },
  {
    id: "masada_sunrise",
    title: "טיפוס למצדה בזריחה דרך שביל הנחש",
    description: "טפסו אל מצדה בשעות הבוקר המוקדמות לפני שהשמש קופחת וזכו לראות את הזריחה המרהיבה מעל ים המלח.",
    category: "שטח",
    difficulty: "בינוני",
    xpReward: 450,
    participantsCount: 95,
    duration: "חד פעמי",
    creator: "רשות הטבע והגנים",
    image: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=600&auto=format&fit=crop&q=80",
    difficultyGrades: [3, 2, 3],
    isIconic: true,
    badgeReward: "🌅 מטפס מצדה"
  },
  {
    id: "eilat_bay_swim",
    title: "צליחת מפרץ אילת במים פתוחים",
    description: "חצו בשחייה את המים הצלולים של מפרץ אילת למרחק של 5 קילומטרים.",
    category: "אירובי",
    difficulty: "קשה",
    xpReward: 750,
    participantsCount: 19,
    duration: "חד פעמי",
    creator: "מועדון השחייה אילת",
    image: "https://images.unsplash.com/photo-1502680390469-be75c86b636f?w=600&auto=format&fit=crop&q=80",
    difficultyGrades: [4, 4, 5],
    isIconic: true,
    badgeReward: "🐠 כריש המפרץ"
  },
  {
    id: "half_israman",
    title: "חצי איש ברזל ישראמן אילת",
    description: "שחייה של 1.9 ק\"מ, רכיבה מאתגרת של 90 ק\"מ ברי הפטריות, וריצה של 21.1 ק\"מ.",
    category: "אירובי",
    difficulty: "קשה מאוד",
    xpReward: 900,
    participantsCount: 22,
    duration: "חד פעמי",
    creator: "התאחדות הטריאתלון",
    image: "https://images.unsplash.com/photo-1530541930197-ff16ac917b0e?w=600&auto=format&fit=crop&q=80",
    difficultyGrades: [5, 4, 5],
    isIconic: true,
    badgeReward: "🥈 חצי איש הברזל"
  },
  {
    id: "sovev_emek_100",
    title: "אולטרה מרתון סובב עמק - 100 ק\"מ",
    description: "ריצת שטח מטורפת לאורך 100 קילומטרים בגבעות עמק יזרעאל והרי מנשה.",
    category: "אירובי",
    difficulty: "קשה מאוד",
    xpReward: 1600,
    participantsCount: 6,
    duration: "חד פעמי",
    creator: "סובב עמק",
    image: "https://images.unsplash.com/photo-1476480862126-209bfaa8edc8?w=600&auto=format&fit=crop&q=80",
    difficultyGrades: [5, 5, 5],
    isIconic: true,
    badgeReward: "🐺 זאב הערבה"
  },
  {
    id: "hermon_cycle",
    title: "מרוץ האופניים לעליית החרמון",
    description: "טפסו על אופני כביש מתחתית הר החרמון ועד לרכבל העליון - 31 ק\"מ של עליות תלולות במיוחד.",
    category: "אירובי",
    difficulty: "קשה מאוד",
    xpReward: 850,
    participantsCount: 11,
    duration: "חד פעמי",
    creator: "אופני החרמון",
    image: "https://images.unsplash.com/photo-1485965120184-e220f721d03e?w=600&auto=format&fit=crop&q=80",
    difficultyGrades: [5, 5, 4],
    isIconic: true,
    badgeReward: "🚴 מטפס העל"
  },
  {
    id: "pullups_1000_m",
    title: "אתגר 1000 עליות מתח בחודש",
    description: "מבחן כוח עליון לפלג הגוף העליון. בצעו 1000 עליות מתח מושלמות במצטבר לאורך 30 יום.",
    category: "כוח",
    difficulty: "קשה",
    xpReward: 800,
    participantsCount: 54,
    duration: "30 ימים",
    creator: "רועי כהן",
    image: "https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=600&auto=format&fit=crop&q=80",
    difficultyGrades: [4, 4, 4],
    isIconic: true,
    badgeReward: "🐒 מלך המתח"
  },
  {
    id: "israel_trail_full",
    title: "טרק שביל ישראל מלא ברצף",
    description: "חצו את כל המדינה מצפון לדרום דרך שביל ישראל - כ-1000 קילומטרים של שטח מגוון.",
    category: "שטח",
    difficulty: "קשה מאוד",
    xpReward: 2500,
    participantsCount: 4,
    duration: "40 ימים",
    creator: "החברה להגנת הטבע",
    image: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=600&auto=format&fit=crop&q=80",
    difficultyGrades: [5, 5, 5],
    isIconic: true,
    badgeReward: "🇮🇱 שביליסט מוסמך"
  },
  {
    id: "ramon_crater_run",
    title: "ריצת שטח במכתש רמון",
    description: "ריצה אתגרית של 30 קילומטרים בתוך הנוף המדברי המהפנט של מכתש רמון.",
    category: "שטח",
    difficulty: "קשה מאוד",
    xpReward: 900,
    participantsCount: 14,
    duration: "חד פעמי",
    creator: "מועדון ריצה רמון",
    image: "https://images.unsplash.com/photo-1476480862126-209bfaa8edc8?w=600&auto=format&fit=crop&q=80",
    difficultyGrades: [5, 4, 5],
    isIconic: true,
    badgeReward: "🏜️ נווד המדבר"
  },
  {
    id: "detox_30d",
    title: "30 ימי מדיטציה וניקוי גוף",
    description: "אתגר יומיומי המשלב 20 דקות מדיטציה, תזונה נקייה והימנעות ממסכים בשעות הערב.",
    category: "זן",
    difficulty: "קל",
    xpReward: 500,
    participantsCount: 78,
    duration: "30 ימים",
    creator: "מיכל אשד",
    image: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=600&auto=format&fit=crop&q=80",
    difficultyGrades: [2, 2, 1],
    isIconic: true,
    badgeReward: "🧘 רוח טהורה"
  },
  {
    id: "deadlift_2x",
    title: "שיא כוח: דדליפט פי 2 ממשקל הגוף",
    description: "הרם משקל של פי שניים ממשקל גופך פעם אחת בטכניקה נקייה לחלוטין.",
    category: "כוח",
    difficulty: "קשה",
    xpReward: 700,
    participantsCount: 29,
    duration: "חד פעמי",
    creator: "מועדון הולמס פלייס עזריאלי",
    image: "https://images.unsplash.com/photo-1574680096145-d05b474e2155?w=600&auto=format&fit=crop&q=80",
    difficultyGrades: [4, 5, 4],
    isIconic: true,
    badgeReward: "🔱 הרקולס"
  },
  {
    id: "plank_10m",
    title: "בטן מפלדה: פלאנק של 10 דקות",
    description: "החזיקו במצב פלאנק קלאסי למשך 10 דקות רצופות ללא נפילה. מבחן מנטלי ופיזי קיצוני.",
    category: "ליבה",
    difficulty: "קשה מאוד",
    xpReward: 900,
    participantsCount: 15,
    duration: "חד פעמי",
    creator: "שירה אלוני",
    image: "https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=600&auto=format&fit=crop&q=80",
    difficultyGrades: [5, 5, 5],
    isIconic: true,
    badgeReward: "🛡️ בטן פלדה"
  },
  {
    id: "freedive_20m",
    title: "צלילה חופשית לעומק 20 מטר",
    description: "רדו לעומק של 20 מטר בנשימה אחת במים הכחולים של הים האדום באילת.",
    category: "שטח",
    difficulty: "קשה",
    xpReward: 700,
    participantsCount: 12,
    duration: "חד פעמי",
    creator: "התאחדות הצלילה",
    image: "https://images.unsplash.com/photo-1502680390469-be75c86b636f?w=600&auto=format&fit=crop&q=80",
    difficultyGrades: [4, 4, 4],
    isIconic: true,
    badgeReward: "🐬 בן המצולות"
  },
  {
    id: "yoga_100d",
    title: "100 ימים רצופים של יוגה",
    description: "בצעו תרגול יוגה של 30 דקות לפחות בכל יום במשך 100 ימים ברצף ללא הפסקה.",
    category: "זן",
    difficulty: "בינוני",
    xpReward: 600,
    participantsCount: 34,
    duration: "100 ימים",
    creator: "נטע ברק",
    image: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=600&auto=format&fit=crop&q=80",
    difficultyGrades: [3, 3, 3],
    isIconic: true,
    badgeReward: "☯️ מסטר יוגה"
  }
];

export const initialFeed = [
  {
    id: "feed_1",
    userId: "user_1",
    userName: "רועי כהן",
    userAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80",
    challengeTitle: "אתגר ריצת 10 קילומטר",
    achievementDetail: "השלמתי את ה-10 קילומטרים בזמן שיא של 44:21 דקות! 🔥🏃‍♂️ ההרגשה מטורפת. מי מנסה לעקוף אותי?",
    proofImage: "https://images.unsplash.com/photo-1502224562085-639556652f33?w=600&auto=format&fit=crop&q=80",
    likes: 24,
    claps: 12,
    hasLiked: false,
    hasClapped: false,
    timestamp: "לפני שעתיים",
    streak: 7,
    comments: [
      {
        id: "c_1",
        userName: "יובל לוי",
        text: "קצב מטורף רועי! כל הכבוד 💪"
      },
      {
        id: "c_2",
        userName: "שירה אלוני",
        text: "השראה לכולנו! ⚡"
      }
    ]
  },
  {
    id: "feed_2",
    userId: "user_2",
    userName: "יובל לוי",
    userAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=80",
    challengeTitle: "100 שכיבות סמיכה ברצף",
    achievementDetail: "סוף סוף הצלחתי! 100 שכיבות סמיכה נקיות. הידיים רועדות אבל זה שווה את זה. 💪🏅",
    proofImage: "https://images.unsplash.com/photo-1598971861713-54ad16a7e72e?w=600&auto=format&fit=crop&q=80",
    likes: 18,
    claps: 22,
    hasLiked: false,
    hasClapped: false,
    timestamp: "לפני 4 שעות",
    streak: 5,
    comments: [
      {
        id: "c_3",
        userName: "דניאל מזרחי",
        text: "סט אחד בלי הפסקה בכלל? וואו."
      }
    ]
  },
  {
    id: "feed_3",
    userId: "user_3",
    userName: "דניאל מזרחי",
    userAvatar: "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=100&auto=format&fit=crop&q=80",
    challengeTitle: "טיפוס לפסגת החרמון",
    achievementDetail: "כבשתי את החרמון! הנוף משוגע, האוויר קפוא והחוויה בלתי נשכחת. 🏔️👣",
    proofImage: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=600&auto=format&fit=crop&q=80",
    likes: 31,
    claps: 40,
    hasLiked: false,
    hasClapped: false,
    timestamp: "לפני יום",
    streak: 3,
    comments: []
  },
  {
    id: "feed_4",
    userId: "user_4",
    userName: "שירה אלוני",
    userAvatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&auto=format&fit=crop&q=80",
    challengeTitle: "30 ימי פלאנק",
    achievementDetail: "יום 15 של הפלאנק! הגעתי כבר ל-3 וחצי דקות פלאנק רצוף! אל תוותרו לעצמכם! ✨🧘‍♀️",
    proofImage: "https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=600&auto=format&fit=crop&q=80",
    likes: 15,
    claps: 10,
    hasLiked: false,
    hasClapped: false,
    timestamp: "לפני יומיים",
    streak: 12,
    comments: []
  },
  {
    id: "feed_5",
    userId: "user_1",
    userName: "רועי כהן",
    userAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80",
    challengeTitle: "יוגה בוקר מרעננת",
    achievementDetail: "45 דקות של מתיחות וריכוז. להתחיל את היום מאוזן ומפוקס 🧘‍♂️✨",
    proofImage: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=600&auto=format&fit=crop&q=80",
    likes: 12,
    claps: 8,
    hasLiked: false,
    hasClapped: false,
    timestamp: "לפני 3 שעות",
    streak: 7,
    comments: []
  },
  {
    id: "feed_6",
    userId: "user_2",
    userName: "יובל לוי",
    userAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=80",
    challengeTitle: "אימון אופניים 20 ק\"מ",
    achievementDetail: "רכיבה מהירה בטיילת, הרוח בשיער והשרירים שורפים 🚲🔥",
    proofImage: "https://images.unsplash.com/photo-1485965120184-e220f721d03e?w=600&auto=format&fit=crop&q=80",
    likes: 19,
    claps: 15,
    hasLiked: false,
    hasClapped: false,
    timestamp: "לפני 5 שעות",
    streak: 5,
    comments: []
  },
  {
    id: "feed_7",
    userId: "user_3",
    userName: "דניאל מזרחי",
    userAvatar: "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=100&auto=format&fit=crop&q=80",
    challengeTitle: "אימון שחייה מהיר",
    achievementDetail: "שברתי את השיא האישי שלי ב-1000 מטר שחייה חופשית! 🏊‍♂️⏱️",
    proofImage: "https://images.unsplash.com/photo-1600965962102-9d260a71890d?w=600&auto=format&fit=crop&q=80",
    likes: 22,
    claps: 18,
    hasLiked: false,
    hasClapped: false,
    timestamp: "לפני 6 שעות",
    streak: 3,
    comments: []
  },
  {
    id: "feed_8",
    userId: "user_4",
    userName: "שירה אלוני",
    userAvatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&auto=format&fit=crop&q=80",
    challengeTitle: "אימון כוח משקולות",
    achievementDetail: "אימון כוח עצים היום, מתחילה להרגיש את השינוי בכוח של פלג גוף עליון 💪🏋️‍♀️",
    proofImage: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=600&auto=format&fit=crop&q=80",
    likes: 17,
    claps: 14,
    hasLiked: false,
    hasClapped: false,
    timestamp: "לפני 8 שעות",
    streak: 12,
    comments: []
  },
  {
    id: "feed_9",
    userId: "user_1",
    userName: "רועי כהן",
    userAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80",
    challengeTitle: "טיול שטח בהרי ירושלים",
    achievementDetail: "15 קילומטרים של עליות וירידות בנוף מהמם. הרגליים עבדו קשה! 🥾⛰️",
    proofImage: "https://images.unsplash.com/photo-1501555088652-021faa106b9b?w=600&auto=format&fit=crop&q=80",
    likes: 26,
    claps: 20,
    hasLiked: false,
    hasClapped: false,
    timestamp: "לפני 12 שעות",
    streak: 7,
    comments: []
  },
  {
    id: "feed_10",
    userId: "user_2",
    userName: "יובל לוי",
    userAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=80",
    challengeTitle: "אימון בטן עצים",
    achievementDetail: "שורף בבטן! 20 דקות של תרגילים אינטנסיביים ⚡🔥",
    proofImage: "https://images.unsplash.com/photo-1566241477600-ac026ad43874?w=600&auto=format&fit=crop&q=80",
    likes: 14,
    claps: 11,
    hasLiked: false,
    hasClapped: false,
    timestamp: "לפני יום",
    streak: 5,
    comments: []
  },
  {
    id: "feed_11",
    userId: "user_3",
    userName: "דניאל מזרחי",
    userAvatar: "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=100&auto=format&fit=crop&q=80",
    challengeTitle: "עליית מתח רצופה",
    achievementDetail: "הצלחתי להגיע ל-20 עליות מתח נקיות בסט אחד! 💪🎯",
    proofImage: "https://images.unsplash.com/photo-1598971639058-fab3c3109a00?w=600&auto=format&fit=crop&q=80",
    likes: 21,
    claps: 16,
    hasLiked: false,
    hasClapped: false,
    timestamp: "לפני יום",
    streak: 3,
    comments: []
  },
  {
    id: "feed_12",
    userId: "user_4",
    userName: "שירה אלוני",
    userAvatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&auto=format&fit=crop&q=80",
    challengeTitle: "מדיטציית שקיעה",
    achievementDetail: "שחרור סוף היום מול השקיעה המדהימה. רוגע ושלווה פנימית 🌅🧘‍♀️",
    proofImage: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=600&auto=format&fit=crop&q=80",
    likes: 30,
    claps: 25,
    hasLiked: false,
    hasClapped: false,
    timestamp: "לפני יומיים",
    streak: 12,
    comments: []
  }
];

export const initialStories = [
  {
    id: "story_1",
    userId: "user_1",
    userName: "רועי כהן",
    userAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80",
    slides: [
      {
        id: "slide_1_1",
        title: "ריצת 10 קילומטר",
        text: "מתחילים את הבוקר בריצה חזקה בפארק! 🏃‍♂️💪",
        image: "https://images.unsplash.com/photo-1476480862126-209bfaa8edc8?w=600&auto=format&fit=crop&q=80",
        timestamp: "לפני שעה"
      },
      {
        id: "slide_1_2",
        title: "הוכחה והישגים",
        text: "44:21 דקות. ה-XP שלי עולה! הצטרפו לאתגר שלי!",
        image: "https://images.unsplash.com/photo-1502224562085-639556652f33?w=600&auto=format&fit=crop&q=80",
        timestamp: "לפני שעה"
      }
    ]
  },
  {
    id: "story_2",
    userId: "user_2",
    userName: "יובל לוי",
    userAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=80",
    slides: [
      {
        id: "slide_2_1",
        title: "100 שכיבות סמיכה ברצף",
        text: "מתכונן לסט המושלם... הצלחתי! 💯",
        image: "https://images.unsplash.com/photo-1598971861713-54ad16a7e72e?w=600&auto=format&fit=crop&q=80",
        timestamp: "לפני 4 שעות"
      }
    ]
  },
  {
    id: "story_3",
    userId: "user_3",
    userName: "דניאל מזרחי",
    userAvatar: "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=100&auto=format&fit=crop&q=80",
    slides: [
      {
        id: "slide_3_1",
        title: "טיפוס לחרמון",
        text: "הנוף פשוט משוגע מכאן למעלה 🏔️🦅",
        image: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=600&auto=format&fit=crop&q=80",
        timestamp: "לפני 5 שעות"
      }
    ]
  },
  {
    id: "story_4",
    userId: "user_4",
    userName: "שירה אלוני",
    userAvatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&auto=format&fit=crop&q=80",
    slides: [
      {
        id: "slide_4_1",
        title: "30 ימי פלאנק",
        text: "יום 15 - כבר מרגישה את החוזק בליבה! 🧘‍♀️✨",
        image: "https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=600&auto=format&fit=crop&q=80",
        timestamp: "לפני 8 שעות"
      }
    ]
  }
];
